<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEg5s7XO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEg5s7XO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEg5s7XO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEg5s7XO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEg5s7XO\App_KernelDevDebugContainer([
    'container.build_hash' => 'Eg5s7XO',
    'container.build_id' => '8ccc7f6f',
    'container.build_time' => 1576871419,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEg5s7XO');
